"""Update match to include min players to ready.

Revision ID: 3d5477aad91e
Revises: f3e41326bbc5
Create Date: 2019-12-05 11:29:05.315175

"""

# revision identifiers, used by Alembic.
revision= '3d5477aad91e'
down_revision = 'f3e41326bbc5'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('min_player_ready', sa.Integer(), nullable=True, default=5))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'min_player_ready')
    ### end Alembic commands ###
