"""Include Team Audit Table.

Revision ID: 4e186245e39b
Revises: 9c8269330b3d
Create Date: 2019-04-23 05:02:15.470544

"""

# revision identifiers, used by Alembic.
revision = '4e186245e39b'
down_revision = '9c8269330b3d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tAudit',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=4), nullable=True),
    sa.Column('logo', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('old_auths', sa.BLOB(), nullable=True),
    sa.Column('new_auths', sa.BLOB(), nullable=True),
    sa.Column('date_changed', mysql.TIMESTAMP(), server_default=sa.text(u'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.execute("CREATE TRIGGER team_audit AFTER UPDATE ON team FOR EACH ROW BEGIN INSERT INTO tAudit values(OLD.id, OLD.user_id, OLD.`name`, OLD.flag, OLD.logo, OLD.auths, NEW.auths, CURRENT_TIMESTAMP); END;")    
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER team_audit;')
    op.drop_table('tAudit')
    ### end Alembic commands ###
