"""Create team auth normalized table.

Revision ID: 79a7336b76fc
Revises: 254a3741efe3
Create Date: 2019-10-28 17:59:01.716518

"""

# revision identifiers, used by Alembic.
revision = '79a7336b76fc'
down_revision = '254a3741efe3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_auth_names',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('team_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('auth', mysql.VARCHAR(length=17), nullable=False),
        sa.Column('name', mysql.VARCHAR(length=40), nullable=True),
        sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset=u'utf8mb4',
        mysql_engine=u'InnoDB'
        )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_auth_names')
    ### end Alembic commands ###
