"""empty message

Revision ID: 9c8269330b3d
Revises: 2482c93c3461
Create Date: 2019-04-22 07:32:27.519833

"""

# revision identifiers, used by Alembic.
revision = '9c8269330b3d'
down_revision = '2482c93c3461'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_audit',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('timeaffected', sa.DateTime(), nullable=True),
    sa.Column('cmd_used', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    


def downgrade():
    
    op.drop_table('match_audit')
    ### end Alembic commands ###
