"""Include SSH model.

Revision ID: ae2ba46fe1a2
Revises: 4e186245e39b
Create Date: 2019-05-02 05:08:50.813840

"""

# revision identifiers, used by Alembic.
revision = 'ae2ba46fe1a2'
down_revision = '4e186245e39b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.add_column('game_server', sa.Column('ssh_user', sa.String(128), default='', nullable=True))
    op.add_column('game_server', sa.Column('ssh_password', sa.String(128), default='', nullable=True))
    op.add_column('game_server', sa.Column('ssh_passwordless', sa.Boolean(), default=False))
    


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_server', 'ssh_user')
    op.drop_column('game_server', 'ssh_password')
    op.drop_column('game_server', 'ssh_passwordless')
    ### end Alembic commands ###
