"""Moving demoFile from match to map stats.

Revision ID: bc790ce2c7b1
Revises: df582b0bd1b2
Create Date: 2019-06-04 22:54:51.982506

"""

# revision identifiers, used by Alembic.
revision = 'bc790ce2c7b1'
down_revision = 'df582b0bd1b2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'demoFile')
    op.add_column('map_stats', sa.Column('demoFile', mysql.VARCHAR(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('demoFile', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('map_stats', 'demoFile')
    ### end Alembic commands ###
