"""Add in knife for sides option to send to API.

Revision ID: df582b0bd1b2
Revises: 2feddad6830a
Create Date: 2019-05-30 05:20:11.199637

"""

# revision identifiers, used by Alembic.
revision = 'df582b0bd1b2'
down_revision = '2feddad6830a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('side_type', sa.String(32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'side_type')
    ### end Alembic commands ###
