"""Update to normalize spectator auths, remove from using pickletypes.

Revision ID: f3e41326bbc5
Revises: 79a7336b76fc
Create Date: 2019-11-06 19:42:59.892408

"""

# revision identifiers, used by Alembic.
revision = 'f3e41326bbc5'
down_revision = '79a7336b76fc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_spectator',
        sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column('match_id', mysql.INTEGER(display_width=11), nullable=False),
        sa.Column('auth', mysql.VARCHAR(length=17), nullable=False),
        sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
        sa.PrimaryKeyConstraint('id'),
        mysql_default_charset=u'utf8mb4',
        mysql_engine=u'InnoDB'
        )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_spectator')
    ### end Alembic commands ###
